export const events = [
  {
    image: "/images/event1.png",
    title: "React Summit US 2025",
    slug: "react-summit-us-2025",
    location: "San Francisco, CA, USA",
    date: "2025-11-07",
    time: "09:00 AM",
  },
  {
    image: "/images/event2.png",
    title: "Next.js Global Conference",
    slug: "nextjs-global-conference",
    location: "New York, NY, USA",
    date: "2025-09-18",
    time: "10:30 AM",
  },
  {
    image: "/images/event3.png",
    title: "AI & Web Dev Expo",
    slug: "ai-web-dev-expo",
    location: "London, UK",
    date: "2025-08-12",
    time: "11:00 AM",
  },
  {
    image: "/images/event4.png",
    title: "Full Stack Fest",
    slug: "full-stack-fest-2025",
    location: "Berlin, Germany",
    date: "2025-10-05",
    time: "02:00 PM",
  },
  {
    image: "/images/event5.png",
    title: "JavaScript World Summit",
    slug: "javascript-world-summit",
    location: "Toronto, Canada",
    date: "2025-07-22",
    time: "01:30 PM",
  },
  {
    image: "/images/event6.png",
    title: "Frontend Masters Meetup",
    slug: "frontend-masters-meetup",
    location: "Sydney, Australia",
    date: "2025-12-01",
    time: "04:00 PM",
  },
];
